WIP: Adding freeze/thaw of containers
Pelagicore/softwarecontainer pull request #133
Opened 2016-11-04 09:32 UTC by tobsan

LXC supports freeze/unfreeze in its lib, this exposes a high-level API
all the way up to D-Bus. Documentation and commenting is still missing
and probably a couple of interesting test cases.

Signed-off-by: Tobias Olausson <tobias.olausson@pelagicore.com>

2016-11-04 10:18 UTC, DunderRoffe requested changes

2016-11-04 10:18 UTC, DunderRoffe commented on agent/softwarecontainer-agent.xml
> +        <method name="ThawContainer">
I think we can have better names for "freeze" and "thaw" that are less tied to LXC. For instance "pause" and "unpause". The point is  that we might want to consider what wording we use before pushing it into our API.

2016-11-04 10:18 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
> +        if (isError(status)) {
We usually put the action inside of the "isError()" function.

2016-11-04 10:18 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
>              deleteContainer(containerID);
Why do we delete the container before we analyze the result of shutdown.
Also why do we not check the status of delete.

2016-11-04 10:18 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
>      if (m_shutdownContainers) {
Negating this if clause and putting a return inside would reduce the indentation

2016-11-04 10:18 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
> +    return false;
It is a bit weird to do all the error handling in the end. Consider negating the above if clause and do the error handling there instead.

2016-11-04 10:18 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.h
> +    bool thawContainer(ContainerID containerID);
Please add documentation

2016-11-04 10:18 UTC, DunderRoffe commented on agent/unit-test/softwarecontaineragent_unittest.cpp
> +    int m_preloadCount = 0;
Why no preloaded containers? It is good to test.

2016-11-04 10:18 UTC, DunderRoffe commented on libsoftwarecontainer/src/container.cpp
> +        // TODO: Is this really the case?
Wat

2016-11-04 10:19 UTC, tobsan commented on agent/softwarecontainer-agent.xml
> +        <method name="ThawContainer">
Sure. The LXC names are freeze and unfreeze btw.

2016-11-04 12:21 UTC, breakreturn requested changes
I think we are missing:
- user-docs updates
- service-tests

2016-11-04 12:21 UTC, breakreturn commented on agent/softwarecontainer-agent.xml
> +        <method name="ThawContainer">
Suspend/Resume ?

2016-11-04 12:21 UTC, breakreturn commented on agent/src/softwarecontaineragent.cpp
> +        if (isError(status)) {
I think this is more explicit and nice.

2016-11-04 12:21 UTC, breakreturn commented on libsoftwarecontainer/include/softwarecontainer.h
> +     */
I don't know the answer, but isn't there more to say about this?

2016-11-04 12:41 UTC, tobsan commented on libsoftwarecontainer/src/container.cpp
> +        // TODO: Is this really the case?
I mean does a thawed container automatically become running. Docs does not seem to have a good answer for that.

2016-11-04 12:43 UTC, tobsan commented on agent/unit-test/softwarecontaineragent_unittest.cpp
> +    int m_preloadCount = 0;
It gives weird output when doing shutdown, since we will always have an unused container. I think we can test the preloading separately (currently we have no such tests).

2016-11-04 12:52 UTC, tobsan commented on agent/src/softwarecontaineragent.cpp
>              deleteContainer(containerID);
Good point, will update that.

2016-11-04 12:53 UTC, tobsan commented on agent/src/softwarecontaineragent.cpp
> +    return false;
I agree, I've added early fail everywhere in the agent now.

2016-11-04 13:24 UTC, tobsan commented on agent/softwarecontainer-agent.xml
> +        <method name="ThawContainer">
Alright, suspend/resume it is!

2016-11-04 13:24 UTC, tobsan commented on agent/src/softwarecontaineragent.cpp
>      if (m_shutdownContainers) {
That's right, fixing.

2016-11-04 13:44 UTC, tobsan commented on libsoftwarecontainer/include/softwarecontainer.h
> +     */
Yes, there is. Will do.

2016-11-07 12:51 UTC, DunderRoffe commented on agent/unit-test/softwarecontaineragent_unittest.cpp
> +    int m_preloadCount = 0;
Sure, could you add a small sanity check test trying to start a preloaded container?

2016-11-07 15:39 UTC, tobsan commented
I have added user docs and service tests.

2016-11-08 07:39 UTC, breakreturn commented on agent/src/softwarecontaineragent.cpp
>      // TODO: Would be nice if this could be done async.
The todo here. I think it should be an issue/story if we actually plan to do this, otherwise remove it.

2016-11-08 07:41 UTC, breakreturn commented on agent/src/softwarecontaineragentadaptor.cpp
> +int32_t softwarecontainer::SoftwareContainerAgentAdaptor::LaunchCommand(const int32_t &containerID, const uint32_t &userID, const std::string &commandLine, const std::string &workingDirectory, const
Very long line.

2016-11-08 07:42 UTC, breakreturn commented on agent/src/softwarecontaineragentadaptor.h
> +    int32_t LaunchCommand(const int32_t &containerID, const uint32_t &userID, const std::string &commandLine,
Weird line breakage?

2016-11-08 07:44 UTC, DunderRoffe requested changes
The verbosity of the code is a bit uneven. Also did you not add a test for preloading containers?

2016-11-08 07:44 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
> +    // job->captureStdin();
Why is this commented

2016-11-08 07:44 UTC, DunderRoffe commented on servicetest/suspend/test_suspend.py
> +@pytest.mark.usefixtures("dbus_launch", "agent", "assert_no_proxy")
Why do we need dbus_launch here? The session bus does not seem to be used.

2016-11-08 07:49 UTC, tobsan commented on agent/src/softwarecontaineragent.cpp
>      // TODO: Would be nice if this could be done async.
Story added, good point.

2016-11-08 07:50 UTC, tobsan commented on agent/src/softwarecontaineragent.cpp
> +    // job->captureStdin();
As said in the comment above, having it uncommented leaks an open pipe. We have a story for fixing this.

2016-11-08 07:51 UTC, breakreturn approved these changes

2016-11-08 07:59 UTC, tobsan commented on agent/src/softwarecontaineragentadaptor.cpp
> +int32_t softwarecontainer::SoftwareContainerAgentAdaptor::LaunchCommand(const int32_t &containerID, const uint32_t &userID, const std::string &commandLine, const std::string &workingDirectory, const
Good point, updating in that whole file.

2016-11-08 08:00 UTC, tobsan commented on agent/src/softwarecontaineragentadaptor.h
> +    int32_t LaunchCommand(const int32_t &containerID, const uint32_t &userID, const std::string &commandLine,
Agreed, changing there as well.

2016-11-08 09:08 UTC, DunderRoffe approved these changes

2016-11-08 09:26 UTC, breakreturn approved these changes

2016-11-08 09:55 UTC, merged