Using GNUInstallDirs to set install paths
Pelagicore/softwarecontainer pull request #145
Opened 2016-11-08 14:44 UTC by DunderRoffe

2016-11-08 15:04 UTC, tobsan requested changes
Just one concrete comment. I see this as a good start for handling the issue on running the agent on the session bus (since that's what you get if installing to a non-/usr prefix.

2016-11-08 15:04 UTC, tobsan commented on CMakeLists.txt
> +add_definitions(-DINSTALL_PREFIX="${CMAKE_INSTALL_FULL_BINDIR}")
If this is already the bindir, why do we add /bin to the setup_softwarecontainer.sh script? Also, it feels a bit misleading to say install prefix, when it is actually the bindir we're adding here.

2016-11-08 15:11 UTC, tobsan commented on CMakeLists.txt
> +add_definitions(-DINSTALL_PREFIX="${CMAKE_INSTALL_FULL_BINDIR}")
Ok my bad (read it as being /bin/bin), but the name is still bad :)

2016-11-09 14:00 UTC, tobsan approved these changes
This looks nice!

2016-11-09 15:05 UTC, tobsan approved these changes

2016-11-09 15:11 UTC, tobsan commented
Just noticing that the troubleshooting chapter in the user docs still mentions that one has to set prefix to /usr, perhaps that should be removed as part of this PR?

2016-11-10 09:23 UTC, tobsan approved these changes

2016-11-10 09:23 UTC, tobsan commented
Just noticing that the troubleshooting chapter in the user docs still mentions that one has to set prefix to /usr, perhaps that should be removed as part of this PR?

2016-11-10 09:43 UTC, breakreturn approved these changes

2016-11-10 09:43 UTC, merged