WIP Add service tests for NetworkGateway
Pelagicore/softwarecontainer pull request #152
Opened 2016-11-10 17:02 UTC by kursatkobya

2016-11-10 17:49 UTC, breakreturn requested changes
A minor comment on style, but in general I think this looks great.

2016-11-10 17:49 UTC, breakreturn commented on servicetest/networkgateway/test_network_gateway.py
> +        """
In all of these, pull up the first text line so it's part of the opening quotes, like you've done in the class comment above.

2016-11-11 07:23 UTC, DunderRoffe approved these changes
Looks really good. It would be cool if we could use some python lib instead of the ping binary though. That would almost entirely remove our need for busybox

2016-11-11 08:39 UTC, breakreturn approved these changes

2016-11-11 08:44 UTC, merged