WIP: Breakout parsers
Pelagicore/softwarecontainer pull request #167
Opened 2016-11-16 17:45 UTC by tobsan

Breaking out parsers for most gateways into their own classes, which can be properly unit tested.

2016-11-18 11:25 UTC, DunderRoffe approved these changes

2016-11-22 13:31 UTC, DunderRoffe approved these changes

2016-11-23 09:25 UTC, breakreturn requested changes

2016-11-23 09:25 UTC, breakreturn commented on libsoftwarecontainer/include/gateway.h
>      static constexpr const char *XDG_RUNTIME_DIR_VARIABLE_NAME = "XDG_RUNTIME_DIR";
While at it, could you also see if the defines make sense to have in the base class?

2016-11-23 09:25 UTC, breakreturn commented on libsoftwarecontainer/unit-test/dbusgatewayparser_unittest.cpp
> +}
Please add descriptive comments to all tests. Everywhere ;)

2016-11-23 09:37 UTC, tobsan commented on libsoftwarecontainer/include/gateway.h
>      static constexpr const char *XDG_RUNTIME_DIR_VARIABLE_NAME = "XDG_RUNTIME_DIR";
Done, it didn't.

2016-11-23 11:22 UTC, tobsan commented on libsoftwarecontainer/unit-test/dbusgatewayparser_unittest.cpp
> +}
Done!

2016-11-23 11:25 UTC, breakreturn approved these changes

2016-11-23 11:25 UTC, merged