WIP : unique IP address
Pelagicore/softwarecontainer pull request #168
Opened 2016-11-17 07:16 UTC by kursatkobya

Generation of unique IP address for each SoftwareContainer
Updates related service test environment

2016-11-17 14:41 UTC, DunderRoffe requested changes

2016-11-17 14:41 UTC, DunderRoffe commented on libsoftwarecontainer/src/gateway/networkgateway.h
> +
why the extra whitespace

2016-11-17 14:41 UTC, DunderRoffe commented on libsoftwarecontainer/src/softwarecontainer.cpp
> +SoftwareContainer::SoftwareContainer(std::shared_ptr<Workspace> workspace, const ContainerID id) :
Would be nice to have the string prefix as well here or maybe the ContainerID type should be changed to a std::string.

2016-11-17 14:49 UTC, kursatkobya commented on libsoftwarecontainer/src/softwarecontainer.cpp
> +SoftwareContainer::SoftwareContainer(std::shared_ptr<Workspace> workspace, const ContainerID id) :
I couldn't reason it, i think agent shouldn't deal with LXC related id. 
The idea of changing id to integer was spin-off from stand-up to get rid of comparision in gateways.

2016-11-18 08:40 UTC, DunderRoffe approved these changes

2016-11-18 08:48 UTC, breakreturn approved these changes

2016-11-18 08:48 UTC, merged