WIP : Add gateway ip and netmask
Pelagicore/softwarecontainer pull request #169
Opened 2016-11-18 09:54 UTC by kursatkobya

Adding gateway ip and network mask bits input to NetworkGateway constructor

2016-11-18 11:37 UTC, breakreturn commented on libsoftwarecontainer/src/gateway/networkgateway.cpp
> +    m_netmask = (1L<<(32-maskBits));
I would appreciate more comments around these parts.

2016-11-18 11:37 UTC, breakreturn commented on libsoftwarecontainer/unit-test/networkgateway_unittest.cpp
> +    MockNetworkGateway():NetworkGateway(11,"10.0.3.1", 0) {}
Spaces here and above. :D

2016-11-18 14:41 UTC, DunderRoffe approved these changes

2016-11-18 14:41 UTC, DunderRoffe commented on libsoftwarecontainer/src/gateway/networkgateway.cpp
> +    m_netmask = (1L<<(32-maskBits));
I think you should write the magic numbers in hex or binary when dealing with bits

2016-11-18 14:42 UTC, tobsan requested changes

2016-11-18 14:42 UTC, tobsan commented on libsoftwarecontainer/src/gateway/networkgateway.cpp
> +        return;
I would like to see an exception being thrown here actually.

2016-11-18 14:53 UTC, kursatkobya commented on libsoftwarecontainer/src/gateway/networkgateway.cpp
> +        return;
Good idea, consider it done.

2016-11-21 11:16 UTC, tobsan commented on libsoftwarecontainer/src/gateway/networkgateway.cpp
> +    m_netmask = (1L<<(32-maskBits));
A comment about this would be helpful.

2016-11-21 11:17 UTC, tobsan commented on libsoftwarecontainer/src/softwarecontainer.cpp
> +        log_error() << "inappropriate netmask";
This error message could be made clearer.

2016-11-21 11:18 UTC, breakreturn approved these changes

2016-11-21 11:28 UTC, kursatkobya commented on libsoftwarecontainer/src/gateway/networkgateway.cpp
> +    m_netmask = (1L<<(32-maskBits));
There is a huge comment block explaining the snippet. I just didn't want over-commenting. But surely i can add a comment if you don't think the comment above is not sufficient.

2016-11-21 11:34 UTC, breakreturn commented on libsoftwarecontainer/src/gateway/networkgateway.cpp
> +    m_netmask = (1L<<(32-maskBits));
I suggest you move the part from the block comment that is about the last line so it reads nicer totally, i.e split the comment up to be aligned with the organization of the code.

2016-11-21 11:57 UTC, merged