WIP: Proposal for SC general config
Pelagicore/softwarecontainer pull request #184
Opened 2016-11-24 17:04 UTC by breakreturn

This is a stubbed proposal for a general config design. The intention is not to have the code in the headers etc. Design wise the intention is to have a "config loader" be responsible for creating the underlying Glibmm object and that the loader and Config class know about Glibmm details, but not the user of Config.

2016-11-24 17:33 UTC, tobsan commented on common/config.h
> + * Propose we have this inherit a general SoftwareContainer exception instead
Why is this not in the softwarecontainer namespace instead?

2016-11-24 17:33 UTC, tobsan commented on common/unit-test/config_unittest.cpp
> +};
This fixture class isn't very useful. Consider moving your instantiation of the loader and config objects into the fixture class.

2016-11-24 17:33 UTC, tobsan commented on common/unit-test/config_unittest.cpp
> +    ASSERT_THROW(config.getStringValue("SoftwareContainer", "does-not-exist"), SCException::ConfigError);
You are testing similar things here. You could consider having the test being value parameterized on group and key if there are many of these tests later on.

2016-12-01 15:55 UTC, DunderRoffe commented on CMakeLists.txt
> -add_subdirectory(libsoftwarecontaineragent)
This could be a separate small pr

2016-12-01 15:59 UTC, DunderRoffe commented on agent/src/main.cpp
> +    int timeout = -1;
Is hanging indefinitely really a sensible default?

2016-12-01 15:59 UTC, DunderRoffe commented on libsoftwarecontainer/include/workspace.h
> +    Workspace();
I think Workspace should be removed entirely

2016-12-01 16:03 UTC, breakreturn commented on CMakeLists.txt
> -add_subdirectory(libsoftwarecontaineragent)
Yes I know. It's just that I have to fix tests and build errors etc., and I know we are to remove it. I guess this will go away during a rebase soon.

2016-12-01 16:04 UTC, breakreturn commented on agent/src/main.cpp
> +    int timeout = -1;
No it's not. But what would be a sensible default? Some of the configs I think will require us to do sanity checks after the priority and logic of choosing source is done. I.e. this default should only be used to check if the user did something explicit but never propagate downwards.

2016-12-01 16:05 UTC, breakreturn commented on libsoftwarecontainer/include/workspace.h
> +    Workspace();
I was hoping we could do that separately, there's so much scope creep in this change anyway ;)

2016-12-02 07:38 UTC, DunderRoffe commented on CMakeLists.txt
> -add_subdirectory(libsoftwarecontaineragent)
Update: Done in another pr by @tobsan

2016-12-02 07:39 UTC, DunderRoffe commented on libsoftwarecontainer/include/workspace.h
> +    Workspace();
sure

2016-12-02 14:50 UTC, tobsan requested changes
1) Fix conflicts
2) Bump version

Looks good though.

2016-12-02 15:05 UTC, DunderRoffe approved these changes

2016-12-02 15:05 UTC, merged