Support for default capabilities
Pelagicore/softwarecontainer pull request #186
Opened 2016-11-25 13:40 UTC by DunderRoffe

2016-11-25 14:07 UTC, breakreturn approved these changes

2016-11-25 14:17 UTC, tobsan requested changes

2016-11-25 14:17 UTC, tobsan commented on agent/src/capability/filteredconfigstore.cpp
> +        conf.append(configByID(id));
Check the return value here before appending, since configByID can fail?

2016-11-25 14:17 UTC, tobsan commented on agent/src/capability/filteredconfigstore.h
> +     * @return GatewayConfiguration maped by the given ID.
mapped*

2016-11-25 14:17 UTC, tobsan commented on agent/src/softwarecontaineragent.cpp
> +        log_error() << "Could noteset gateway configuration for capability"
typo

2016-11-25 14:17 UTC, tobsan commented on agent/src/softwarecontaineragent.cpp
> +                    << std::to_string(containerID) << " does not exist";
Is this the only case where it would fail?

2016-11-25 14:17 UTC, tobsan commented on common/gatewayconfig.cpp
> +    for (auto &i : m_configMap) {
i is a bad variable name imho

2016-11-25 14:17 UTC, tobsan commented on doc/chapters/integration-guidelines/index.rst
> +or not. Each manifest are expected to be of type JSON, including the "json" file extension.
Shouldn't this be ${FULL_SYSCONFDIR}/softwarecontainer/...? We can do substitutions from cmake to the sphinx config file for things like this, please do.

2016-11-25 14:25 UTC, DunderRoffe commented on agent/src/capability/filteredconfigstore.cpp
> +        conf.append(configByID(id));
Is it not better to return all found things instead of empty when something fails?

2016-11-25 14:25 UTC, DunderRoffe commented on agent/src/capability/filteredconfigstore.h
> +     * @return GatewayConfiguration maped by the given ID.
Fixed

2016-11-25 14:26 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
> +        log_error() << "Could noteset gateway configuration for capability"
fixed

2016-11-25 14:27 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
> +                    << std::to_string(containerID) << " does not exist";
probably not, removing extra row

2016-11-25 14:29 UTC, DunderRoffe commented on common/gatewayconfig.cpp
> +    for (auto &i : m_configMap) {
Changing to "it" then since. It is an iterator afterall

2016-11-28 09:17 UTC, tobsan commented on agent/src/capability/filteredconfigstore.cpp
> +        conf.append(configByID(id));
I think we should aim for failing early in case of errors, so I would go for that - wanting an unexisting cap is an error imho.

2016-11-28 12:27 UTC, merged