Revise NetworkGateway configuration
Pelagicore/softwarecontainer pull request #187
Opened 2016-11-29 14:37 UTC by kursatkobya

- NetworkGateway configuration is revised due to whitelisting policy.
- NetworkGatewayParser is evolved accordingly with its unit tests.
- iptableentry is extended with multiple protocol support feauture.
- service tests are updated and also 
- Gateway documentation has been updated with corresponding changes

2016-11-29 15:07 UTC, thenor commented on doc/chapters/gateways/index.rst
> +the rule applies to all ports.  ``ports`` are valid between 0 and 65536. There are threee valid values for ``protocols``:
Too many e:s in "three". :)

2016-11-29 15:13 UTC, thenor commented on doc/chapters/gateways/index.rst
> +NetworkGateway is programmed to drop all packages that does not match any entry in ``allow`` list.
"do" (not "does")

2016-11-29 15:15 UTC, thenor commented on doc/chapters/gateways/index.rst
> +Following is an example attempting to reject all ping requests except example.com. Only port 53 on tcp and udp protocols
I think it would be better to write "The following is an example which rejects all ping requests..." (without "attempts to")

2016-11-30 08:00 UTC, tobsan approved these changes

2016-11-30 08:00 UTC, tobsan commented on libsoftwarecontainer/src/gateway/network/networkgatewayparser.cpp
> +                return ReturnCode::FAILURE;
Couldn't you break out the protocol parsing into a metthod, since you're doing the same thing for a single and for an array of protocols?

2016-11-30 09:02 UTC, DunderRoffe requested changes
Minor things

2016-11-30 09:02 UTC, DunderRoffe commented on libsoftwarecontainer/src/gateway/network/networkgatewayparser.cpp
> +                            << " is not appropriate only tcp, udp and icmp protocol are alllowed";
change "appropriate" to "valid value"

2016-11-30 09:02 UTC, DunderRoffe commented on libsoftwarecontainer/unit-test/iptableentry_unittest.cpp
> +            " -j ACCEPT", ipTable.interpretRuleWithProtocol(r, r.protocols[0]));
indentation

2016-11-30 09:02 UTC, DunderRoffe commented on libsoftwarecontainer/unit-test/iptableentry_unittest.cpp
> +            " -j ACCEPT", ipTable.interpretRuleWithProtocol(r, r.protocols[0]));
indentation

2016-11-30 09:02 UTC, DunderRoffe commented on libsoftwarecontainer/unit-test/iptableentry_unittest.cpp
> +            " -j ACCEPT", ipTable.interpretRuleWithProtocol(r, r.protocols[0]));
indentation

2016-11-30 09:07 UTC, thenor commented on libsoftwarecontainer/src/gateway/network/networkgatewayparser.cpp
> +    json_t *port = json_object_get(element, "ports");
Is this a list of ports or a single port? The use of both "port" and "ports" is confusing to me.

2016-11-30 09:07 UTC, thenor commented on libsoftwarecontainer/src/gateway/network/networkgatewayparser.cpp
> +    json_t *protocol = json_object_get(element, "protocols");
Same as above. The use of both singular and plural is a bit confusing to me.

2016-11-30 09:08 UTC, thenor commented on libsoftwarecontainer/src/gateway/network/networkgatewayparser.cpp
> +                        << " is not appropriate only tcp, udp and icmp protocol are alllowed";
Typo: 3 l:s in "allowed"

2016-11-30 09:08 UTC, kursatkobya commented on libsoftwarecontainer/src/gateway/network/networkgatewayparser.cpp
> +    json_t *port = json_object_get(element, "ports");
this can be either a single port or ports, user decides it

2016-11-30 09:09 UTC, thenor commented on libsoftwarecontainer/src/gateway/network/networkgatewayparser.cpp
> +                log_error() << "Inappropriate protocol is listeed";
Typo: 2 e:s in "listed"

2016-11-30 09:09 UTC, thenor commented on libsoftwarecontainer/src/gateway/network/networkgatewayparser.cpp
> +                            << " is not appropriate only tcp, udp and icmp protocol are alllowed";
Typo: 3 l:s in "allowed"

2016-11-30 09:09 UTC, kursatkobya commented on libsoftwarecontainer/src/gateway/network/networkgatewayparser.cpp
> +    json_t *protocol = json_object_get(element, "protocols");
same as above maybe i should rename the json variable. consider it done

2016-11-30 09:10 UTC, DunderRoffe commented on libsoftwarecontainer/src/gateway/network/networkgatewayparser.cpp
> +    json_t *port = json_object_get(element, "ports");
It is both

2016-11-30 09:10 UTC, DunderRoffe commented on libsoftwarecontainer/src/gateway/network/networkgatewayparser.cpp
> +    json_t *protocol = json_object_get(element, "protocols");
It is both

2016-11-30 09:15 UTC, thenor commented on libsoftwarecontainer/src/gateway/network/networkgatewayparser.cpp
> +    json_t *port = json_object_get(element, "ports");
If it can be "1 or more" then I think using "ports" is better.

2016-11-30 09:22 UTC, DunderRoffe approved these changes

2016-11-30 09:27 UTC, thenor approved these changes

2016-11-30 14:53 UTC, merged