Envgateway supports prepend+append
Pelagicore/softwarecontainer pull request #190
Opened 2016-12-01 11:57 UTC by tobsan

Some changes in filegateway were done as a consequence of this.

2016-12-01 12:59 UTC, breakreturn commented on doc/chapters/gateways/index.rst
> +- ``separator``: A string that will be squeezed in between the old and new value if one wants to
Squeezed? Could use more boring but "correct" language :)

2016-12-01 15:47 UTC, DunderRoffe requested changes

2016-12-01 15:47 UTC, DunderRoffe commented on doc/chapters/gateways/index.rst
> +            "mode": "append"
Make "append" big letters or non case sensitive

2016-12-01 16:37 UTC, tobsan commented on doc/chapters/gateways/index.rst
> +            "mode": "append"
Making it case insensitive seems reasonable, I'm doing that.

2016-12-02 07:36 UTC, DunderRoffe approved these changes
Awesomesauce

2016-12-02 07:36 UTC, merged