run_all_tests.sh is no longer available, run tests separately
Pelagicore/softwarecontainer pull request #217
Opened 2016-12-12 11:58 UTC by frznlogic

2016-12-12 12:03 UTC, tobsan requested changes
I'm not sure we want to run all examples automatically, but apart from that this looks good.

2016-12-13 08:22 UTC, thenor commented on Vagrantfile
> +                   sudo ./run-tests.sh
Shouldn't this be "run-tests.py"?

2016-12-13 08:43 UTC, frznlogic commented on Vagrantfile
> +                   sudo ./run-tests.sh
You are correct. Fixed.

2016-12-13 08:44 UTC, frznlogic commented
@tobsan would you like me to remove the whole section instead? It's currently inside a if ENV['BUILD_AND_TEST'] then so it's not run by default.

2016-12-13 08:45 UTC, thenor approved these changes

2016-12-13 08:59 UTC, tobsan commented
@frznlogic yes, automatically building and testing is done by the Jenkinsfile nowadays anyway.

2016-12-13 09:10 UTC, frznlogic commented
@tobsan updated documentation and removed the section completely.

2016-12-13 09:22 UTC, thenor commented on README.md
>  to run them as root, since the actual container creation is not stubbed of
Please take the opportunity to fix the "of" typo. It should be "off", or not included at all.

2016-12-13 09:34 UTC, frznlogic commented on README.md
>  to run them as root, since the actual container creation is not stubbed of
done.

2016-12-13 09:39 UTC, DunderRoffe approved these changes

2016-12-13 10:48 UTC, tobsan approved these changes

2016-12-13 10:48 UTC, merged