agent: set default caps if gateways not configured
Pelagicore/softwarecontainer pull request #241
Opened 2016-12-19 13:09 UTC by tobsan

The only way to have the gateways configured from the agent is through
setCapabilities, so if they are not configured, then that call has not
been made, and the default caps have not been applied.

Signed-off-by: Tobias Olausson <tobias.olausson@pelagicore.com>

2016-12-19 13:44 UTC, breakreturn requested changes

2016-12-19 13:44 UTC, breakreturn commented on agent/src/softwarecontaineragent.cpp
> +    // since we then should get only the default ones.
For multi line comments it would be more consistent with the rest of the code to use:
/*
 *
 */

2016-12-19 14:23 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
> +    // since we then should get only the default ones.
I think it is nice to not use that when writing something that should not end up in the API docs as it looks different from the doxygen comments. On the other hand, this might be useful in the API if tweaked a bit?

2016-12-19 14:53 UTC, breakreturn commented on agent/src/softwarecontaineragent.cpp
> +    // since we then should get only the default ones.
Do you mean you see a risk that it might be interpreted by someone as a doxygen comment and lead to confusion? AFAIK the most consistent choice now would be to use /* */ based on the rest of the code.

2016-12-19 15:16 UTC, tobsan commented on agent/src/softwarecontaineragent.cpp
> +    // since we then should get only the default ones.
FYI this will not be interpreted by doxygen.

2016-12-20 11:09 UTC, breakreturn commented on servicetest/capabilities/test_caps.py
> +                        ])
The list is missing one space indentation.

2016-12-20 11:12 UTC, breakreturn commented on servicetest/capabilities/test_caps.py
> +                                  " --do-get-env-vars")
Indentation looks off

2016-12-20 11:13 UTC, breakreturn commented on servicetest/capabilities/test_caps.py
> +    def test_no_caps_gives_default_only(self):
This name is off, it should be something like "test_defaults_are_applied" or something, as it doesn't test any interaction between set caps and default caps, the test result would be the same even if there was some cap set.

2016-12-20 12:02 UTC, breakreturn approved these changes

2016-12-20 12:02 UTC, merged