WIP: Debugging documentation
Pelagicore/softwarecontainer pull request #244
Opened 2016-12-20 11:10 UTC by frznlogic

2016-12-20 12:10 UTC, tobsan reviewed
Looks good so far!

2017-01-31 10:01 UTC, tobsan requested changes
Have some inline comments, but something that I think should be added is the case where someone uses SC on an embedded system and works on an app on their workstation. A setup with gdb-server would be nice to be able to show. Perhaps it is super simple and it would just suffice to state "it is also possible to use gdb-server" or something.

2017-01-31 10:01 UTC, tobsan commented on doc/chapters/debugging/index.rst
> +`SoftwareContainer` will also delete all container instances upon startup,
Maybe we should mention that this is done by the agent.

2017-01-31 10:01 UTC, tobsan commented on doc/chapters/debugging/index.rst
> +be saved to a bind mounted directory before you shut down the container.
Perhaps a bit misleading wording. Restarting an app is not necessarily the same as destroying the container and starting a new one, although that is probably what will happen most of the time.

2017-01-31 10:01 UTC, tobsan commented on doc/chapters/debugging/index.rst
> +    sudo lxc-attach --name SC-X ps aux
Why the sudo? You had a section above that one needs to be the right user anyway.

2017-01-31 10:01 UTC, tobsan commented on doc/chapters/debugging/index.rst
> +TODO: Uncertain why, but this fails with unable to find executable.
Could it be that in our containers ls is a shell builtin and not a binary? Not sure if that is the case.

2017-01-31 10:01 UTC, tobsan commented on doc/chapters/debugging/index.rst
> +    # sudo gdb --pid XXX /tmp/container//SC-0/gateways/app/main
This assumes that the app will always be in a directory that is reachable from the host. That is probably a good idea to suggest though, but it is not a requirement when running an app.

2017-01-31 10:01 UTC, tobsan commented on doc/chapters/debugging/index.rst
> +able to connect to the process inside the container.
Is there no way around this at all? That sucks a bit :/.

2017-01-31 10:01 UTC, tobsan commented on doc/chapters/debugging/index.rst
> +`QtCreator` or `GDB`. Load the file as normal.
When we've done work on generating core dumps, I will update this section I guess.

2017-01-31 10:01 UTC, tobsan commented on doc/chapters/debugging/index.rst
> +TODO: Do we actually receive backtraces from something? Not sure what this means
Aren't those part of a core dump?

2017-01-31 10:01 UTC, tobsan commented on doc/chapters/debugging/index.rst
> +as of this writing.
We could add that one can use ivi-logging with DLT as backend.

2017-01-31 10:01 UTC, tobsan commented on doc/chapters/debugging/index.rst
> +TODO: Not sure what to write here?
Part of core dumps, right?

2017-01-31 11:40 UTC, frznlogic commented on doc/chapters/debugging/index.rst
> +be saved to a bind mounted directory before you shut down the container.
The base filesystem is deleted AFAICR? Anyways, added a note that most of the filesystems should be bind mounted anyways.

2017-01-31 11:40 UTC, frznlogic commented on doc/chapters/debugging/index.rst
> +`SoftwareContainer` will also delete all container instances upon startup,
Added.

2017-01-31 11:40 UTC, frznlogic commented on doc/chapters/debugging/index.rst
> +    sudo lxc-attach --name SC-X ps aux
Removed, keeping it in the gdb example though as I think it's not quite the same type of example.

2017-01-31 11:40 UTC, frznlogic commented on doc/chapters/debugging/index.rst
> +TODO: Uncertain why, but this fails with unable to find executable.
I don't think so. I had the same issue with other applications as well... and gdb does not read shell builtins in that way anyways afaik.

2017-01-31 11:41 UTC, frznlogic commented on doc/chapters/debugging/index.rst
> +    # sudo gdb --pid XXX /tmp/container//SC-0/gateways/app/main
Not sure that I understand this? you mean if the filesystem is bind mounted from somewhere on a network mount or...?

2017-01-31 11:47 UTC, frznlogic commented on doc/chapters/debugging/index.rst
> +able to connect to the process inside the container.
I dont think so, but I haven't looked into ways around it really. It's part of the security model of Linux imho, and being able to debug a root app from a non-root app would be strongly discouraged imho.

2017-01-31 11:47 UTC, frznlogic commented on doc/chapters/debugging/index.rst
> +`QtCreator` or `GDB`. Load the file as normal.
I did generate a core dump and debugged it... basically, it works as you would expect, nothing special needed :)

2017-01-31 11:47 UTC, frznlogic commented on doc/chapters/debugging/index.rst
> +TODO: Do we actually receive backtraces from something? Not sure what this means
Ok :) So basically nothing extra required then. Removing it.

2017-01-31 11:47 UTC, frznlogic commented on doc/chapters/debugging/index.rst
> +as of this writing.
True =) I've added some blurb about it at least.

2017-01-31 11:47 UTC, frznlogic commented on doc/chapters/debugging/index.rst
> +TODO: Not sure what to write here?
Removing it in that case.

2017-01-31 11:55 UTC, tobsan commented on doc/chapters/debugging/index.rst
> +be saved to a bind mounted directory before you shut down the container.
Yes, the rootfs is deleted IF we delete the container. My point was that deleting the container is not always necessary in order to restart an app (but one will probably do that anyway)

2017-01-31 11:57 UTC, tobsan commented on doc/chapters/debugging/index.rst
> +    # sudo gdb --pid XXX /tmp/container//SC-0/gateways/app/main
I mean that one can bind-mount to any location in the container, in which case we first mount into /gateways, and then move the mount (to some place which the host can't easily access). Will the gdb chroot trick still work then?

2017-01-31 12:06 UTC, frznlogic commented on doc/chapters/debugging/index.rst
> +be saved to a bind mounted directory before you shut down the container.
Ah, I see your point. Rewriting it now to indicate container being destroyed/recreated.

2017-01-31 12:10 UTC, frznlogic commented on doc/chapters/debugging/index.rst
> +    # sudo gdb --pid XXX /tmp/container//SC-0/gateways/app/main
It depends, if you do really funky shit with the chroot, it wont work... IMHO, I'm not sure it's possible for us to take every single variation into account though... I guess it's up to the user to solve those problems in that case... no?

2017-01-31 12:36 UTC, tobsan commented on doc/chapters/debugging/index.rst
> +    # sudo gdb --pid XXX /tmp/container//SC-0/gateways/app/main
Yeah, I guess so.

2017-01-31 12:37 UTC, tobsan approved these changes
Looks good, but would be nice to get rid of those TODOs if possible.

2017-01-31 13:33 UTC, merged