Fixes for missing dependencies
Pelagicore/softwarecontainer pull request #250
Opened 2016-12-21 13:43 UTC by dzudek

During the native build, a compiling and linking errors occurs due to missing dependencies in CMake files. With those small changes I'm able to do a native build (checked on Ubuntu 16.04).

2016-12-21 14:49 UTC, tobsan approved these changes

2016-12-21 14:51 UTC, tobsan requested changes
Please add a sign-off line so that we get a DCO as well.

You can add such a line by issuing "git commit --amend -s" on the commits.

See CONTRIBUTING.md

2017-01-03 18:23 UTC, dzudek commented
Thanks @tobsan , Got it.

2017-01-04 08:35 UTC, tobsan approved these changes

2017-01-04 08:36 UTC, merged