Add Whitelist policy to CGroups Gateway
Pelagicore/softwarecontainer pull request #259
Opened 2017-01-04 12:16 UTC by kursatkobya

Whitelisting feauture implemented on cgroupparser
	Related unittests are added
	User dics has updated

2017-01-04 12:47 UTC, tobsan approved these changes
Looks good!

2017-01-04 12:47 UTC, tobsan commented on libsoftwarecontainer/src/gateway/cgroups/cgroupsparser.cpp
> +            // if the new value is lexicographical greater than old one set is as the value
This is not lexicographically comparison :)

2017-01-04 12:59 UTC, kursatkobya commented on libsoftwarecontainer/src/gateway/cgroups/cgroupsparser.cpp
> +            // if the new value is lexicographical greater than old one set is as the value
I just change it to integer comparision after deciding to apply only one setting

2017-01-04 13:14 UTC, breakreturn requested changes

2017-01-04 13:14 UTC, breakreturn commented on libsoftwarecontainer/src/gateway/cgroups/cgroupsparser.cpp
> +        log_warning() << "It is possible to apply this rule through control groups of working "
I think this should be more specific and clear, e.g. "cgroups gateway config \"" <<  config << "\" is not supported by the gateway"

2017-01-04 13:19 UTC, kursatkobya commented on libsoftwarecontainer/src/gateway/cgroups/cgroupsparser.cpp
> +        log_warning() << "It is possible to apply this rule through control groups of working "
But kernel can support this setting so maybe it is not told that its not supported. But we can keep saying this setting is not guaranteed to work by cgroup gateway. But i agree we should mentioned about the key. Thus i propose to keep sentence but changing "this rule" part with the actual setting key.

2017-01-05 08:27 UTC, DunderRoffe approved these changes

2017-01-05 08:38 UTC, breakreturn approved these changes

2017-01-05 09:40 UTC, merged