Add servicetest for list containers
Pelagicore/softwarecontainer pull request #261
Opened 2017-01-04 14:41 UTC by thenor

2017-01-04 20:03 UTC, tobsan requested changes
Except for the manifest comment, my only issue is that I don't think it is pythonic to put parenthesis around tuples that are returned (or when matching). Do like this instead.

return a,b
a,b = blah()

2017-01-04 20:03 UTC, tobsan commented on servicetest/general/test_general.py
> +}]
It does not make much sense to keep this config here, it should work with empty manifests as well I guess.

2017-01-05 11:33 UTC, thenor commented on servicetest/general/test_general.py
> +}]
Ok. I just felt it was more "service test" like for me to have a mimimal manifest, but I can also remove it completely since I don't need the config in it. I will at least try not having it.

2017-01-05 11:35 UTC, thenor commented
To comment here also, and not just in person, I attempted to not use parenthesis, but I got an error. When I added the parenthesis it worked so I kept it that way. I will see if I can find a nice way to remove the parenthesis.

2017-01-05 12:34 UTC, thenor commented on servicetest/testframework/lib.py
> +        return (self.__container_id, success)
What doesn't work is this:
        return self.__agent.Create(config)
But I can remove the parenthesis and return more than one value.

2017-01-05 14:18 UTC, thenor commented on servicetest/general/test_general.py
> +}]
I realized I didn't do anything with this in my latest update. I can try clearing it.

2017-01-05 16:19 UTC, tobsan approved these changes

2017-01-09 08:05 UTC, thenor commented
The last update is just a squash for nicer commits, to avoid the "updated after comments" like commit.

2017-01-09 10:05 UTC, merged