WIP Buffered mount point implementation
Pelagicore/softwarecontainer pull request #27
Opened 2016-09-20 07:32 UTC by frznlogic

This is still work in progress, comments are welcome however.

2016-09-20 07:36 UTC, tobsan commented on common/softwarecontainer-common.cpp
> +}
Is this tmpdir cleaned up on exit, like the other things in this class? If not - it should be!

2016-09-20 10:28 UTC, DunderRoffe requested changes
Work in progress

2016-09-20 10:44 UTC, DunderRoffe commented on common/softwarecontainer-common.cpp
> +    auto mountRes = mount   (path.c_str(), path.c_str(), "", MS_BIND, nullptr);
Why the whitespaces ?

2016-09-20 10:48 UTC, DunderRoffe commented on common/softwarecontainer-common.h
> +    std::string tempDir(std::string templ);
Maybe we should make the functions virtual in order to be able to mock them?

2016-09-20 10:50 UTC, DunderRoffe commented on libsoftwarecontainer/src/container.cpp
> +            overlayMount(rootfspath_lower, rootfspath_upper, rootfspath_work, rootfspath_dst);
Do these strings have to be mutable ? If not please make them const :)

2016-09-20 10:53 UTC, DunderRoffe commented on common/unit-test/CMakeLists.txt
> +			cat $TMP_FILE | sed -r 's/^\\[\\s+OK\\s+\\] (.*) \\([0-9]+\\sms\\)$/PASS: \\1 /' | sed -r 's/^\\[\\s+FAILED\\s+\\] (.*) \\([0-9]+\\sms\\)$/FAIL: \\1 /' | awk '{if ($1 == \"PASS:\" || $1 == \"FAIL:
Please consider splitting this line into multiple lines, it is really hard to read.

2016-09-20 10:55 UTC, DunderRoffe commented on common/softwarecontainer-common.h
> +    std::string tempDir(std::string templ);
Also, please provide documentation for `tempDir()`

2016-09-20 10:58 UTC, DunderRoffe requested changes
Looks good in general but there are some things to look at

2016-09-20 11:09 UTC, frznlogic commented on common/softwarecontainer-common.cpp
> +    auto mountRes = mount   (path.c_str(), path.c_str(), "", MS_BIND, nullptr);
My bad.

2016-09-20 11:09 UTC, frznlogic commented on common/softwarecontainer-common.h
> +    std::string tempDir(std::string templ);
Documentation added.

2016-09-20 11:16 UTC, frznlogic commented on libsoftwarecontainer/src/container.cpp
> +            overlayMount(rootfspath_lower, rootfspath_upper, rootfspath_work, rootfspath_dst);
Nope. done.

2016-09-20 11:16 UTC, frznlogic commented on common/unit-test/CMakeLists.txt
> +			cat $TMP_FILE | sed -r 's/^\\[\\s+OK\\s+\\] (.*) \\([0-9]+\\sms\\)$/PASS: \\1 /' | sed -r 's/^\\[\\s+FAILED\\s+\\] (.*) \\([0-9]+\\sms\\)$/FAIL: \\1 /' | awk '{if ($1 == \"PASS:\" || $1 == \"FAIL:
This is a copy paste. we should probably centralize the entire macro also. It's probably the third time i did the copy...

2016-09-20 11:42 UTC, frznlogic commented on common/unit-test/CMakeLists.txt
> +			cat $TMP_FILE | sed -r 's/^\\[\\s+OK\\s+\\] (.*) \\([0-9]+\\sms\\)$/PASS: \\1 /' | sed -r 's/^\\[\\s+FAILED\\s+\\] (.*) \\([0-9]+\\sms\\)$/FAIL: \\1 /' | awk '{if ($1 == \"PASS:\" || $1 == \"FAIL:
Better now I think.

2016-09-20 11:44 UTC, DunderRoffe approved these changes

2016-09-20 11:48 UTC, tobsan commented on common/softwarecontainer-common.cpp
> +    if (dir == NULL) {
Can we use nullptr instead here?

2016-09-20 11:54 UTC, tobsan commented on libsoftwarecontainer/include/container.h
> +     * @brief Calls lxc-stop (force stop)
Can we change this to saying that it calls stop on the lxc container?

2016-09-20 11:56 UTC, tobsan commented on libsoftwarecontainer/src/container.cpp
> +            const std::string rootfspath_work = StringBuilder() << rootfspath_lower << "-work";
Is there a reason we're using StringBuilder() instead of just str1 + str2?

2016-09-20 11:58 UTC, tobsan commented on libsoftwarecontainer/lxc-softwarecontainer.in
> +        -b|--buffer)    buffer="true";;
It looks like the buffer variable is not used anywhere inside the template, so what is it doing there?

2016-09-20 11:58 UTC, tobsan requested changes
Looks good in general, see separate comments for change requests.

2016-09-20 12:04 UTC, frznlogic commented on common/softwarecontainer-common.cpp
> +    if (dir == NULL) {
yupp

2016-09-20 12:06 UTC, frznlogic commented on libsoftwarecontainer/include/container.h
> +     * @brief Calls lxc-stop (force stop)
Sure. I didn't really bother with double checking all the old comments so there might be more problems with the actual comments tbh...

2016-09-20 12:11 UTC, frznlogic commented on libsoftwarecontainer/src/container.cpp
> +            const std::string rootfspath_work = StringBuilder() << rootfspath_lower << "-work";
Only for the s_LXCRoot line. It's a char so no std::string functions on it.

2016-09-20 12:17 UTC, frznlogic commented on libsoftwarecontainer/lxc-softwarecontainer.in
> +        -b|--buffer)    buffer="true";;
Removed. Thanks for pointing it out.

2016-09-21 14:12 UTC, breakreturn commented on cmake_modules/AddGTestTest.cmake
> +        install(FILES "${CMAKE_CURRENT_BINARY_DIR}/run-ptest" DESTINATION ${TESTS_INSTALLATION_PATH}
This looks like it is indented too far.

2016-09-21 14:12 UTC, breakreturn commented on common/softwarecontainer-common.cpp
> +
Remove empty line.

2016-09-21 14:13 UTC, breakreturn commented on common/softwarecontainer-common.cpp
> +
Too many empty lines.

2016-09-21 14:15 UTC, breakreturn commented on common/softwarecontainer-common.cpp
> +        const std::string &lower
The style guidelines says the comma should be displaced so the following code aligns with the first param.

2016-09-21 14:18 UTC, breakreturn commented on common/unit-test/CMakeLists.txt
> +set(TEST_LIBRARY_DEPENDENCIES
Mixing space before parenthesis and no space before.

2016-09-21 14:19 UTC, breakreturn commented on common/unit-test/softwarecontainer-common_unittest.cpp
> +    void SetUp() override
The placement of the curlies should be consistent. I prefer the above where the empty body is put on the same line.

2016-09-21 14:19 UTC, frznlogic commented on cmake_modules/AddGTestTest.cmake
> +        install(FILES "${CMAKE_CURRENT_BINARY_DIR}/run-ptest" DESTINATION ${TESTS_INSTALLATION_PATH}
No. cmake write Bash syntax stuff. I cant fix it.

2016-09-21 14:20 UTC, breakreturn commented on libsoftwarecontainer/unit-test/CMakeLists.txt
> +include (AddGTestTest)
Again inconsistency with the whitespace. Please take a look throughout if there are more.

2016-09-21 14:20 UTC, frznlogic commented on common/softwarecontainer-common.cpp
> +
Done.

2016-09-21 14:20 UTC, frznlogic commented on common/softwarecontainer-common.cpp
> +
Done

2016-09-21 14:21 UTC, frznlogic commented on common/softwarecontainer-common.cpp
> +        const std::string &lower
Done.

2016-09-21 14:22 UTC, frznlogic commented on common/unit-test/CMakeLists.txt
> +set(TEST_LIBRARY_DEPENDENCIES
Done.

2016-09-21 14:22 UTC, frznlogic commented on common/unit-test/softwarecontainer-common_unittest.cpp
> +    void SetUp() override
Done.

2016-09-21 14:22 UTC, frznlogic commented on libsoftwarecontainer/unit-test/CMakeLists.txt
> +include (AddGTestTest)
Done.

2016-09-21 14:33 UTC, merged