SoftwareContainer Exceptions
Pelagicore/softwarecontainer pull request #274
Opened 2017-01-12 12:39 UTC by thenor

Add an internal SoftwareContainer exception class and
remove internal throwing of ReturnCode.

2017-01-13 11:44 UTC, tobsan requested changes

2017-01-13 11:44 UTC, tobsan commented on agent/src/softwarecontaineragent.cpp
> +        throw SoftwareContainerAgentError();
It would make sense to use the message that we log as message to the exception also, in all places in this file.

2017-01-13 11:44 UTC, tobsan commented on agent/src/softwarecontaineragent.h
> +        return SoftwareContainerAgentError::m_message.c_str();
Since you're inheriting `SoftwareContainerAgentError`, you should return `m_message.c_str()` instead.

2017-01-13 11:44 UTC, tobsan commented on agent/src/softwarecontaineragent.h
> +        return SoftwareContainerAgentError::m_message.c_str();
Use `m_message.c_str()` here also, and in all the places in this file where you inherit something where m_message is protected.

2017-01-13 12:00 UTC, thenor commented on agent/src/softwarecontaineragent.cpp
> +        throw SoftwareContainerAgentError();
I agree. I have already started doing this. Also the exceptions might be called something more specific.

2017-01-13 15:00 UTC, breakreturn commented on agent/src/softwarecontaineragent.h
> +        return SoftwareContainerAgentError::m_message.c_str();
Since the parent is initialized with the message, shouldn't it be enough to just let the method be in the parent and not implement it again here?

2017-01-16 12:07 UTC, thenor commented
I will abandon this pull request and instead create a new one, since team members had dependencies to the SoftwareContainerError base class.

2017-01-16 12:07 UTC, closed without merging