Added Developer section to user docs
Pelagicore/softwarecontainer pull request #28
Opened 2016-09-20 12:10 UTC by breakreturn

A "developer guidelines" is added to the user docs
and some intralinks added to other sections.

2016-09-20 13:41 UTC, tobsan commented on doc/chapters/developers/index.rst
> +The desgin intention is to have this interface container technology agnostic. The design is intended to:
typo, desgin

2016-09-20 13:43 UTC, tobsan commented on doc/chapters/developers/index.rst
> +* Separate maintennance between gateways, e.g. updating the config and implementation of one doesn't ripple to the others.
typo, maintennance

2016-09-20 13:44 UTC, tobsan requested changes

2016-09-21 05:32 UTC, breakreturn commented
Updated the commit with the typo fixes

2016-09-21 05:42 UTC, DunderRoffe commented on doc/chapters/developers/index.rst
> +or anyone that simply wants a better insight for e.g. troubleshooting.
Who instead of that both line 9 and 10

2016-09-21 05:52 UTC, DunderRoffe commented on doc/chapters/developers/index.rst
> +access the container interface. The interface is implemented by ``SoftwareContainerLib``.
Maybe something like "which users can use to access the container"  instead of "so users can access...."

2016-09-21 05:58 UTC, DunderRoffe commented on doc/chapters/getting-started/index.rst
> +Throughout this section, we will create a container, run a command in it and then shut down the
Also destroying it is presume ?

2016-09-21 06:07 UTC, DunderRoffe reviewed
Some suggestions on wording

2016-09-21 06:50 UTC, merged