Netw-GW takes values from main config
Pelagicore/softwarecontainer pull request #280
Opened 2017-01-16 11:20 UTC by breakreturn

Eventually, the config should probably be passed
to SoftwareContainer, but that has dependencies on some
other structural change which are not part of this commit.
As a middle step towards that, the agent now has the config
as a member but passes the network GW values directly
rather than sharing the config.

Signed-off-by: Joakim Gross <joakim.gross@pelagicore.com>

2017-01-16 11:53 UTC, tobsan requested changes
Code looks good, but I think that netmask-bits should really be 24 and not 16, since it used to be set to 24 in the setup scripts (255.255.255.0). We can of course change to 16, but I don't see why we should.

2017-01-16 12:19 UTC, tobsan approved these changes

2017-01-16 12:19 UTC, tobsan commented
After discussion we decided to look into the 16/24 bits issue separately.

2017-01-16 12:43 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
>                                              ConfigDefinition::SC_PRELOAD_COUNT_KEY);
Fix indentation

2017-01-16 12:43 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
>                                                      ConfigDefinition::SC_KEEP_CONTAINERS_ALIVE_KEY);
Fix indentation

2017-01-16 12:43 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
>                                               ConfigDefinition::SC_SHUTDOWN_TIMEOUT_KEY);
Fix indentation

2017-01-16 12:43 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
>                                                   ConfigDefinition::SC_SHARED_MOUNTS_DIR_KEY);
Fix indentation

2017-01-16 12:43 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
>                                                ConfigDefinition::SC_LXC_CONFIG_PATH_KEY);
Fix indentation

2017-01-16 12:43 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
>                                                     ConfigDefinition::SC_SERVICE_MANIFEST_DIR_KEY);
Fix indentation

2017-01-16 12:43 UTC, DunderRoffe commented on agent/src/softwarecontaineragent.cpp
>                                                            ConfigDefinition::SC_DEFAULT_SERVICE_MANIFEST_DIR_KEY);
Fix indentation

2017-01-17 07:52 UTC, DunderRoffe approved these changes

2017-01-18 09:18 UTC, merged