Remove dbus-c++ dependencies of examples
Pelagicore/softwarecontainer pull request #302
Opened 2017-01-23 14:51 UTC by kursatkobya

Signed-off-by: kursat <kursat.kobya@pelagicore.com>

2017-01-23 14:59 UTC, breakreturn requested changes
Just a minor comment

2017-01-23 14:59 UTC, breakreturn commented on examples/temperature/temperature-service/src/temperatureservice_dbus_common.h
> +    //template <typename T0>
Any reason to keep this and the similar comment below?

2017-01-23 15:06 UTC, DunderRoffe requested changes
Looks really nice overall but a few things:

2017-01-23 15:06 UTC, DunderRoffe commented on examples/temperature/temperature-service-console-client/temperatureserviceinterface.cpp
> +                            sigc::mem_fun(*this,
Would be nice to extract the `mem_fun` stuff to `auto callback = sigc::mem_fun...`

2017-01-23 15:06 UTC, DunderRoffe commented on examples/temperature/temperature-service/src/CMakeLists.txt
Would be nice to have minimum cmake version here

2017-01-23 15:06 UTC, DunderRoffe commented on examples/temperature/temperature-service-console-client/temperatureserviceinterface.cpp
> +                                          &TemperatureServiceInterface::on_gettemp_finished));
Would be nice to extract the `mem_fun` stuff to `auto callback = sigc::mem_fun...`

2017-01-23 15:18 UTC, tobsan requested changes
Looks generally good code-wise, but the client no longer logs to a file from what I can see. Why not?

2017-01-23 15:18 UTC, tobsan commented on examples/temperature/temperature-service-console-client/temperature_dbus_proxy.h
> +#include "../temperature-service/src/temperatureservice_dbus_common.h"
Do you really need this one? Can't you generate this for the client separately?

2017-01-23 15:20 UTC, kursatkobya commented on examples/temperature/temperature-service-console-client/temperature_dbus_proxy.h
> +#include "../temperature-service/src/temperatureservice_dbus_common.h"
i can put same file to client as well but then we had redundant files.

2017-01-23 15:22 UTC, kursatkobya commented on examples/temperature/temperature-service/src/CMakeLists.txt
cmake version is applicable with SC (3.0.2)

2017-01-23 15:53 UTC, DunderRoffe commented on examples/temperature/temperature-service/src/temperatureservice_dbus_common.h
> +    //template <typename T0>
No this should be removed. It is generated  :/

2017-01-23 16:20 UTC, kursatkobya commented on examples/temperature/temperature-service-console-client/temperature_dbus_proxy.h
> +#include "../temperature-service/src/temperatureservice_dbus_common.h"
But after a trial, this include can be removed totally.

2017-01-23 16:34 UTC, DunderRoffe approved these changes

2017-01-23 16:35 UTC, DunderRoffe commented on examples/temperature/temperature-service/src/CMakeLists.txt
Actually it is already present :) nwm

2017-01-24 06:27 UTC, breakreturn approved these changes

2017-01-24 08:31 UTC, tobsan commented
I still don't see this logging to file anywhere. Either fix that, or change the script that runs this example so that a log file is not needed anymore.

2017-01-24 12:28 UTC, tobsan approved these changes

2017-01-24 12:28 UTC, merged