cgroupsgateway: add support for net_cls.classid
Pelagicore/softwarecontainer pull request #338
Opened 2017-02-07 14:50 UTC by tobsan

Signed-off-by: Tobias Olausson <tobias.olausson@pelagicore.com>

2017-02-07 15:03 UTC, DunderRoffe commented on libsoftwarecontainer/src/gateway/cgroups/cgroupsparser.cpp
> +        char *endPtr;
This should be initialized.

2017-02-07 15:40 UTC, DunderRoffe approved these changes

2017-02-08 06:48 UTC, kursatkobya commented on libsoftwarecontainer/src/gateway/cgroups/cgroupsparser.cpp
> +    } else if (("net_cls.classid") == settingKey) {
removing parenthesis on  `("net_cls.classid") `  may be clearer to read here

2017-02-08 06:56 UTC, kursatkobya commented on libsoftwarecontainer/src/gateway/cgroups/cgroupsparser.cpp
> +        if (hexedValue == 0 || hexedValue == ULONG_MAX || ((endPtr != NULL) && *endPtr != '\0')) {
i would prefer `0 == hexedValue` and `ULONG_MAX == hexedValue` here

2017-02-08 07:03 UTC, kursatkobya approved these changes

2017-02-08 07:17 UTC, breakreturn requested changes

2017-02-08 07:17 UTC, breakreturn commented on doc/chapters/gateways/10-cgroups-gateway.rst
> +
I think this should be extended with an example. The example config section doesn't reflect this at all.

2017-02-08 07:22 UTC, kursatkobya approved these changes
Also a service test would be nice

2017-02-08 09:27 UTC, tobsan commented
Updated according to comments. Will add a service test also.

2017-02-08 14:31 UTC, tobsan commented
Added a service test now.

2017-02-09 07:10 UTC, breakreturn requested changes

2017-02-09 07:10 UTC, breakreturn commented on servicetest/cgroups/test_cgroups.py
> +    { "setting": "memory.limit_in_bytes", "value": "1K" }
Spaces after the braces is not how the rest of the code looks, please align with the rest of the code or change everywhere.

2017-02-09 09:37 UTC, tobsan commented on servicetest/cgroups/test_cgroups.py
> +    { "setting": "memory.limit_in_bytes", "value": "1K" }
Sure, changed it back.

2017-02-09 09:52 UTC, breakreturn approved these changes

2017-02-09 11:47 UTC, merged