Remove log_ functions from stuff run in container
Pelagicore/softwarecontainer pull request #348
Opened 2017-02-13 14:09 UTC by tobsan

Currently, due to how DLT works, using ivi-logging with
DLT will disable logging inside containers, and instead
just hang, which is not good. We've cleaned this before,
but missed that it sneaked back in.

Signed-off-by: Tobias Olausson <tobias.olausson@pelagicore.com>

2017-02-13 14:11 UTC, breakreturn approved these changes

2017-02-13 14:54 UTC, rpannek commented on libsoftwarecontainer/src/gateway/network/iptableentry.cpp
> +                    std::cout << "Couldn't apply the rule " << rule.target << std::endl;
Shouldn't you be logging errors into `std::cerr`?

2017-02-13 15:03 UTC, rpannek requested changes

2017-02-13 15:03 UTC, rpannek commented on libsoftwarecontainer/src/gateway/network/iptableentry.cpp
> +            std::cout << "Couldn't apply the rule " << rule.target << std::endl;
Please use std::cerr for error logging.

2017-02-14 09:55 UTC, tobsan commented
Updated as per your requests @rpannek

2017-02-14 10:02 UTC, jeena approved these changes

2017-02-14 10:04 UTC, rpannek approved these changes

2017-02-14 11:05 UTC, merged