iptables/busybox are mounted instead of copied
Pelagicore/softwarecontainer pull request #355
Opened 2017-02-14 17:39 UTC by tobsan

Also adds proc and sys as lxc.mount.auto entries.

Plus some general cleanup in the LXC template

Signed-off-by: Tobias Olausson <tobias.olausson@pelagicore.com>

2017-02-15 13:48 UTC, DunderRoffe requested changes
At a quick glance the content seems nice. However, this should really be broken up in several commits.

2017-02-15 13:53 UTC, frznlogic approved these changes
I approve with some comments and questions.

2017-02-15 13:53 UTC, frznlogic commented on libsoftwarecontainer/lxc-softwarecontainer.in
> -        ${ADDITIONAL_FOLDER_MOUNTS}"
I assume we have no use for this parameter?

2017-02-15 13:53 UTC, frznlogic commented on libsoftwarecontainer/lxc-softwarecontainer.in
> +    # If we have network enabled, we need iptables
Do we really _always_ need it? I'm not going to nitpick about it i guess.

2017-02-15 13:53 UTC, frznlogic commented on libsoftwarecontainer/lxc-softwarecontainer.in
> +    echo "Usage: $(basename $0) -p|--path=<path> --rootfs=<path>"
Why did we remove the usage function? Imho, it could have been expanded with more information and probably looked better than this.

2017-02-15 14:16 UTC, tobsan commented on libsoftwarecontainer/lxc-softwarecontainer.in
> -        ${ADDITIONAL_FOLDER_MOUNTS}"
We don't use it anywhere in the rest of the code base.

2017-02-15 14:16 UTC, tobsan commented on libsoftwarecontainer/lxc-softwarecontainer.in
> +    # If we have network enabled, we need iptables
Yes, if we have network gateway enabled, we will **always** need it.

2017-02-15 14:17 UTC, tobsan commented on libsoftwarecontainer/lxc-softwarecontainer.in
> +    echo "Usage: $(basename $0) -p|--path=<path> --rootfs=<path>"
This template is called from within LXC, so imho this is enough printouts for whoever encounters a problem.

2017-02-15 14:51 UTC, DunderRoffe approved these changes
Assuming you fix the comments from @frznlogic this is ok

2017-02-16 13:54 UTC, frznlogic commented on libsoftwarecontainer/lxc-softwarecontainer.in
> -        ${ADDITIONAL_FOLDER_MOUNTS}"
Ok, I was just considering if it was something that the integrator/user would like to have at some point.

2017-02-16 13:55 UTC, frznlogic approved these changes

2017-02-16 13:55 UTC, merged