Adds tests for using POSIX shared memory
Pelagicore/softwarecontainer pull request #360
Opened 2017-02-16 16:00 UTC by tobsan

It seems that one can mount these entries just as if they were regular files.

Signed-off-by: Tobias Olausson <tobias.olausson@pelagicore.com>

2017-02-16 16:07 UTC, tobsan commented
FYI: this is dependent on #359 and should be rebased on top of that one, once it is in master.

2017-02-17 12:59 UTC, tobsan commented
I have rebased this after #359 was merged. Should be ready for merging now.

2017-02-17 12:59 UTC, tobsan commented on libsoftwarecontainer/component-test/CMakeLists.txt
> +    rt # For SHM tests to work
If anyone knows a nicer way of including this CMake-style, do tell!

2017-02-17 13:12 UTC, DunderRoffe requested changes

2017-02-17 13:12 UTC, DunderRoffe commented on libsoftwarecontainer/component-test/softwarecontainerlib_componenttest.cpp
> +    const char *objName2 = "/testObject2";
I think it is nicer to use
```cpp
const std::string foo = "bar";
someUsage(foo.c_str());
```

2017-02-17 13:12 UTC, DunderRoffe commented on libsoftwarecontainer/component-test/softwarecontainerlib_componenttest.cpp
> +    ASSERT_EQ(jobShm->wait(), EXISTENT);
IIRC we added convenience functions for checking the result of jobs, please use them instead.

2017-02-17 13:12 UTC, DunderRoffe commented on libsoftwarecontainer/component-test/softwarecontainerlib_componenttest.cpp
> +TEST_F(SoftwareContainerApp, TestPOSIXSHM) {
Add comment explaining the purpose of the test

2017-02-17 13:12 UTC, DunderRoffe commented on libsoftwarecontainer/component-test/softwarecontainerlib_componenttest.cpp
> +    ASSERT_EQ(jobShm1->wait(), EXISTENT);
See previous job assert comment.

2017-02-17 13:12 UTC, DunderRoffe commented on libsoftwarecontainer/component-test/softwarecontainerlib_componenttest.cpp
> +    ASSERT_EQ(jobShm2->wait(), NON_EXISTENT);
See previous job assert comment.

2017-02-17 13:12 UTC, DunderRoffe commented on libsoftwarecontainer/component-test/softwarecontainerlib_componenttest.cpp
> +    ASSERT_EQ(jobShm2->wait(), EXISTENT);
See previous job assert comment.

2017-02-17 13:12 UTC, DunderRoffe commented on libsoftwarecontainer/component-test/softwarecontainerlib_componenttest.cpp
> +    ASSERT_EQ(close(fd), 0);
Consider refactor this to remove code duplication. Not sure what would be best for readability but this is a bit messy...

2017-02-17 13:17 UTC, tobsan commented on libsoftwarecontainer/component-test/softwarecontainerlib_componenttest.cpp
> +    const char *objName2 = "/testObject2";
Even though we never use it as a std::string?

2017-02-17 13:19 UTC, DunderRoffe commented on libsoftwarecontainer/component-test/softwarecontainerlib_componenttest.cpp
> +    const char *objName2 = "/testObject2";
yes

2017-02-17 13:20 UTC, DunderRoffe commented on libsoftwarecontainer/component-test/CMakeLists.txt
> +    rt # For SHM tests to work
Sorry I do not know

2017-02-17 15:32 UTC, DunderRoffe approved these changes

2017-02-17 15:58 UTC, merged