Test setting capability twice
Pelagicore/softwarecontainer pull request #366
Opened 2017-02-20 12:57 UTC by thenor

Verify that there are no crashes when setting the same
capability twice. Write a service test to verify this.

Signed-off-by: Therese Nordqvist <therese.nordqvist@pelagicore.com>

2017-02-20 13:18 UTC, DunderRoffe requested changes

2017-02-20 13:18 UTC, DunderRoffe commented on servicetest/capabilities/test_caps.py
> +                sc.set_capabilities(["test.cap.valid-dbus"])
Does this really cover the testcase? The error to catch will still trigger a DBusException with the text "No response" or something ...

2017-02-20 13:20 UTC, thenor commented on servicetest/capabilities/test_caps.py
> +                sc.set_capabilities(["test.cap.valid-dbus"])
Oops. Yes. Will fix.

2017-02-20 13:20 UTC, breakreturn requested changes

2017-02-20 13:20 UTC, breakreturn commented on servicetest/capabilities/test_caps.py
> +        """ Test that setting the same capability doesn't result in crashes
Maybe we can be even a little more clear here, and describe that we are expecting a D-Bus exception of a certain kind and not a crash which results in a timeout error on this end (the client).

2017-02-20 13:23 UTC, thenor commented on servicetest/capabilities/test_caps.py
> +        """ Test that setting the same capability doesn't result in crashes
Alright. I will update it to be more specific. Just as the comment for the error I expect.

2017-02-20 16:09 UTC, DunderRoffe approved these changes

2017-02-21 06:24 UTC, breakreturn commented on servicetest/capabilities/test_caps.py
> +import unittest
This could be removed now I guess?

2017-02-21 13:19 UTC, thenor commented on servicetest/capabilities/test_caps.py
> +import unittest
Yes! Forgot it! Thanks!

2017-02-21 14:40 UTC, breakreturn approved these changes

2017-02-21 14:43 UTC, merged