filesystem docs: Improved description of write buffers
Pelagicore/softwarecontainer pull request #381
Opened 2017-03-10 13:46 UTC by frznlogic

Signed-off-by: Oscar Andreasson <oscar.andreasson@pelagicore.com>

2017-03-10 13:58 UTC, breakreturn approved these changes

2017-03-13 15:32 UTC, tobsan approved these changes

2017-03-13 15:33 UTC, tobsan commented on doc/chapters/filesystem/index.rst
> +          exclusive.
Has this been tested nicely? Trying to mount stuff into a container using overlayfs?

2017-03-14 14:04 UTC, frznlogic commented on doc/chapters/filesystem/index.rst
> +          exclusive.
I believe so? The service tests do this since the bug story was fixed regarding the service tests?

2017-03-14 14:14 UTC, thenor commented on doc/chapters/integration-guidelines/10-write-buffers.rst
> +a short json object that is sent to the SoftwareContainerAgent.Create method.
Keep the same way of writing:
``com.pelagicore.SoftwareContainerAgent.Create(id)``

2017-03-14 14:15 UTC, thenor requested changes
One nit-picky comment for consistency.

2017-03-14 15:11 UTC, frznlogic commented
@thenor fixed!

2017-03-14 15:30 UTC, thenor commented on doc/chapters/filesystem/index.rst
>  config::
Here is write with a different mark-up than the new text. Maybe we should use this for the new chapter also.

2017-03-14 15:30 UTC, thenor commented on doc/chapters/integration-guidelines/10-write-buffers.rst
> +
See comment in filesystem/index.rst

2017-03-14 15:34 UTC, thenor approved these changes

2017-03-14 15:34 UTC, merged