user docs: Add information about cpu.shares
Pelagicore/softwarecontainer pull request #414
Opened 2017-04-06 10:32 UTC by thenor

Signed-off-by: Therese Nordqvist <therese.nordqvist@pelagicore.com>

2017-04-06 11:24 UTC, tobsan requested changes

2017-04-06 11:24 UTC, tobsan commented on doc/chapters/gateways/10-cgroups-gateway.rst
> +            "value": "520"},
This is syntactically incorrect.

2017-04-06 11:24 UTC, tobsan commented on doc/chapters/gateways/10-cgroups-gateway.rst
> +            "value": "800"},
Why the inner object here? It would not be accepted by the gateway afaik.

2017-04-10 06:23 UTC, thenor commented on doc/chapters/gateways/10-cgroups-gateway.rst
> +            "value": "520"},
You are very correct. I made a copy-paste-error.

2017-04-10 07:09 UTC, tobsan approved these changes

2017-04-10 07:13 UTC, breakreturn approved these changes

2017-04-10 07:13 UTC, merged