Docs
Pelagicore/softwarecontainer pull request #417
Opened 2017-04-12 08:44 UTC by breakreturn

2017-04-12 10:14 UTC, thenor commented on doc/chapters/gateways/10-dbus-gateway.rst
>  expected to use these variables (probably by means of the binding used).
Could you please take the opportunity to remove the extra word in the above sentence (second paragraph, 3rd line from the bottom): "The gateway uses **uses** an"

2017-04-12 10:14 UTC, frznlogic approved these changes

2017-04-12 10:31 UTC, thenor commented on doc/chapters/gateways/10-dbus-gateway.rst
> +The ``dbus-proxy``always allow the ``org.freedesktop.DBus`` interface, even if it is not
A space is missing and it should be "allows".

2017-04-12 10:32 UTC, thenor requested changes
Just minor changes requested.

2017-04-12 13:25 UTC, kursatkobya approved these changes

2017-04-13 06:17 UTC, thenor approved these changes

2017-04-13 06:17 UTC, merged