Testing robustness of bindMount
Pelagicore/softwarecontainer pull request #420
Opened 2017-04-18 13:11 UTC by thenor

Add more test cases to verify and cover more cases for bindMount.

Signed-off-by: Therese Nordqvist <therese.nordqvist@pelagicore.com>

2017-04-19 07:15 UTC, breakreturn requested changes

2017-04-19 07:15 UTC, breakreturn commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +// Mount a path which is malformed, e.g. too many "/"
I think the comment should either be indented along with the code inside the test, or located above the test if it's a comment for the whole test. Same goes for some other places below as well.

2017-04-19 07:15 UTC, breakreturn commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +    // Is this ok? Will the extra "/" will be removed?
Is this a "todo" comment, or is it a comment for what's being asserted?

2017-04-19 07:15 UTC, breakreturn commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +// Mount a non-existing path
Is this a comment for what the test does? Put it above the test in that case, and comment on what's being tested, e.g. "Mount a non-existing path and assert that ... "

2017-04-19 07:15 UTC, breakreturn commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +// Mount a non-existing path
Copy pasted from above? Same comment as for above applies here I think.

2017-04-19 07:22 UTC, thenor commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +    // Is this ok? Will the extra "/" will be removed?
Yes this is more or less on the level of a TODO. I saw the printout during the test and couldn't see if this path (with extra slashes) was what was being using for the bindmount command. I wanted to check up if we remove extra slashes (couldn't find it in our code, so perhaps it is the help functions we use). So it was a reminder to myself to check up on it.

2017-04-19 07:23 UTC, thenor commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +// Mount a path which is malformed, e.g. too many "/"
Yes, agreed. I wrote it in the beginning of the test case to specify what to test, then forgot to redo it as a test header/description.

2017-04-19 07:23 UTC, thenor commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +// Mount a non-existing path
Yes, will redo all the comments and move them.

2017-04-24 08:35 UTC, breakreturn commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +        ASSERT_EQ(mkdir(DIR_PATH.c_str(),775),0);
There should be spaces after the commas.

2017-04-24 08:37 UTC, breakreturn commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +        ASSERT_TRUE(createFile(FILE_PATH, FILE_CONTENT));
I'm not a fan of testing things in the test setup. Do we think this can fail? It should be a test in that case, a separate test.

2017-04-24 08:39 UTC, breakreturn commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +    // TODO: Verify that this is not a false positive
Should this be resolved or is it intentionally left?

2017-04-24 08:43 UTC, thenor commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +        ASSERT_TRUE(createFile(FILE_PATH, FILE_CONTENT));
Ok. I will change it to use the regular c++ assert.

2017-04-24 08:50 UTC, thenor commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +    // TODO: Verify that this is not a false positive
I forgot to remove it after I had tested this.

2017-04-24 11:19 UTC, breakreturn approved these changes

2017-04-24 13:05 UTC, kursatkobya approved these changes
looks nice.
approved with small comments

2017-04-24 13:05 UTC, kursatkobya commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +            if (!out.good()) {
just an option, you can get rid of ret variable just by returning good method to have concise function
```
std::ofstream out(path);
if (out.is_open()) {
    out << content;
    return out.good();
}

return false;
```

2017-04-24 13:05 UTC, kursatkobya commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +    const std::string FILE_PATH_W_SPACES = "/tmp/example file name.txt";
this looks like filename with spaces to me.  Adding space after tmp would be more explanatory.
`/tmp /example file/name.txt`

2017-04-24 13:10 UTC, thenor commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +    const std::string FILE_PATH_W_SPACES = "/tmp/example file name.txt";
But that would be a new directory: "tmp\ "
What I wanted was just "/tmp/"+FILE_W_SPACES, whic I could have written.

2017-04-24 13:10 UTC, thenor commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +            if (!out.good()) {
Oh yes of course. Good catch.

2017-04-24 13:13 UTC, thenor commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +            if (!out.good()) {
Hm well... I want to do the out.close also.

2017-04-24 13:35 UTC, kursatkobya commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +            if (!out.good()) {
I think ofstream destructor closes the file but sure

2017-04-24 13:51 UTC, thenor commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +            if (!out.good()) {
Tbh I copied this code from common and didn't analyze it too much. Maybe you are right.

2017-04-24 13:56 UTC, frznlogic approved these changes

2017-04-24 14:30 UTC, kursatkobya commented on libsoftwarecontainer/component-test/filegateway_componenttest.cpp
> +    }
nice !!

2017-04-25 06:23 UTC, merged