agent: only remove containers created by SC
Pelagicore/softwarecontainer pull request #422
Opened 2017-07-24 15:47 UTC by tobsan

Adds a simple regex that checks for container names matching SC-* and if
they don't match - don't remove them.

Signed-off-by: Tobias Olausson <tobias.olausson@pelagicore.com>

2017-07-25 06:51 UTC, DunderRoffe commented on agent/src/containerutilityinterface.cpp
>          delete containerNames[i];
Why are we using two lists instead of a map?

2017-07-25 06:57 UTC, DunderRoffe requested changes
Looks legit. However, I would like to see the following tests as well:

* Starting more than 1 SC container and 1 non-SC container
* Starting them in different orders
* Starting no SC containers

2017-07-25 06:57 UTC, DunderRoffe commented on servicetest/agent/test_agent.py
> +        os.system("lxc-destroy -n " + skipped_container_name)
This cleanup will be skipped it there is an exception (or assertion error) in the code above.

2017-07-25 06:57 UTC, DunderRoffe commented on servicetest/agent/test_agent.py
> +        os.system("lxc-create -t busybox -n " + skipped_container_name)
It might be neater to use the lxc python module for this

2017-07-26 11:07 UTC, tobsan commented on agent/src/containerutilityinterface.cpp
>          delete containerNames[i];
Because the lists are populated through a call to the LXC API.

2017-07-26 11:46 UTC, DunderRoffe commented on agent/src/containerutilityinterface.cpp
>          delete containerNames[i];
sure but that does not mean that we need to keep the data stored that way right?

2017-07-27 15:18 UTC, tobsan commented on agent/src/containerutilityinterface.cpp
>          delete containerNames[i];
No but should we iterate over the data and store it in a different way just because it is convenient?

2017-07-27 15:18 UTC, tobsan commented on servicetest/agent/test_agent.py
> +        os.system("lxc-create -t busybox -n " + skipped_container_name)
Working on it. The LXC bindings for Python are Python3 only, which means some refactoring and updating of the service test code.

2017-07-27 15:18 UTC, tobsan commented on servicetest/agent/test_agent.py
> +        os.system("lxc-destroy -n " + skipped_container_name)
The whole test should have a try/finally

2017-07-28 10:20 UTC, DunderRoffe commented on agent/src/containerutilityinterface.cpp
>          delete containerNames[i];
Convenience sounds like a good reason yes :)
Also it would let you use c++11 style for loops

2017-07-28 10:35 UTC, DunderRoffe requested changes

2017-07-28 10:35 UTC, DunderRoffe commented on servicetest/dbus/dbusapp.py
> +        print(("Got a Ping: ", message))
I prefer `print("Got a Ping {}".format(message))` as it explicitly shows where the message will be inserted

2017-07-28 10:35 UTC, DunderRoffe commented on servicetest/dbus/dbusapp.py
> +        print(("method: ", args.method))
I prefer `print("method: {}".format(args.method))`

2017-07-28 10:35 UTC, DunderRoffe commented on servicetest/dbus/test_dbus.py
> +            print(("Total time:                   {0:.4f} seconds\n".format(t2 - t0)))
Redundant parentheses

2017-07-28 10:35 UTC, DunderRoffe commented on servicetest/filesystem/test_filesystem_strace.py
> +            files = [a for a in files if a != f]
A bit weird to mix standard for loop notation with a list comprehension

2017-07-28 10:35 UTC, DunderRoffe commented on servicetest/timingprofiling/test_profiling.py
> +            print("Start app " + str(app))
Use .format instead of +
https://softwareengineering.stackexchange.com/questions/304445/why-is-s-better-than-for-concatenation

2017-07-28 10:35 UTC, DunderRoffe commented on servicetest/timingprofiling/test_profiling.py
> +    print("Nothing found! " + point_name + " " + str(match_number))
Use .format instead of +
https://softwareengineering.stackexchange.com/questions/304445/why-is-s-better-than-for-concatenation

2017-07-28 10:35 UTC, DunderRoffe commented on servicetest/timingprofiling/test_profiling.py
> +    print("Nothing found! " + function_name + " " + str(match_number))
Use .format instead of +
https://softwareengineering.stackexchange.com/questions/304445/why-is-s-better-than-for-concatenation

2017-07-28 10:35 UTC, DunderRoffe commented on servicetest/timingprofiling/test_profiling.py
> +    print("Nothing found! " + point_name + " " + str(match_number))
Use .format instead of +
https://softwareengineering.stackexchange.com/questions/304445/why-is-s-better-than-for-concatenation

2017-07-28 13:57 UTC, tobsan commented on servicetest/filesystem/test_filesystem_strace.py
> +            files = [a for a in files if a != f]
This was suggested by 2to3, actually.

2017-08-08 08:21 UTC, DunderRoffe approved these changes

2017-08-24 11:47 UTC, DunderRoffe requested changes

2017-08-24 11:47 UTC, DunderRoffe commented on servicetest/testframework/lib.py
> +#        if self.is_alive():
Please clean up comment

2017-08-24 11:47 UTC, DunderRoffe commented on servicetest/agent/test_agent.py
> +                    sc_containers += 1
Make sure that sc is cleaned up if there is a failure

2017-08-29 07:33 UTC, DunderRoffe approved these changes

2017-08-30 07:46 UTC, merged