Adding Jenkins file
Pelagicore/softwarecontainer pull request #58
Opened 2016-10-04 10:41 UTC by frznlogic

2016-10-04 10:43 UTC, tobsan requested changes

2016-10-04 10:43 UTC, tobsan commented on Jenkinsfile
> +def workspace = "/mnt/ssd/jenkins/workspace/SoftwareContainerPipeline"
Can we really have this hard-coded? We should be able to capture the workspace of the first workspace (build stage) and then use that in runInVagrant. I don't know about groovy scripts, but in Jenkins shell scripts you can use ${WORKSPACE}

2016-10-04 10:43 UTC, tobsan commented on Jenkinsfile
> +    sh 'cd /mnt/ssd/jenkins/workspace/SoftwareContainerPipeline && vagrant up --provision'
Also, if we want the workspace variable, it should be used here as well.

2016-10-04 10:44 UTC, DunderRoffe requested changes

2016-10-04 10:44 UTC, DunderRoffe commented on Jenkinsfile
> +def workspace = "/mnt/ssd/jenkins/workspace/SoftwareContainerPipeline"
Seems awfully specific. Will this run on any of the nodes ?

2016-10-04 10:44 UTC, DunderRoffe commented on Jenkinsfile
> +        runInVagrant("cd softwarecontainer/build && sudo ./run-tests.sh")
Are there not problems with running the tests in sudo ?

2016-10-04 10:46 UTC, DunderRoffe commented on Jenkinsfile
> +def workspace = "/mnt/ssd/jenkins/workspace/SoftwareContainerPipeline"
The solution @tobsan suggested sounds good

2016-10-04 11:12 UTC, frznlogic commented on Jenkinsfile
> +def workspace = "/mnt/ssd/jenkins/workspace/SoftwareContainerPipeline"
There is no $WORKSPACE in pipeline scripts unfortunately..... :/

2016-10-04 11:12 UTC, frznlogic commented on Jenkinsfile
> +    sh 'cd /mnt/ssd/jenkins/workspace/SoftwareContainerPipeline && vagrant up --provision'
Yepp, that was the idea ;)

2016-10-04 11:13 UTC, frznlogic commented on Jenkinsfile
> +def workspace = "/mnt/ssd/jenkins/workspace/SoftwareContainerPipeline"
Nope :)

2016-10-04 11:13 UTC, frznlogic commented on Jenkinsfile
> +        runInVagrant("cd softwarecontainer/build && sudo ./run-tests.sh")
aaah, that explains why the pulseaudio test fails perhaps :)

2016-10-05 07:21 UTC, DunderRoffe approved these changes

2016-10-05 07:21 UTC, merged