Fix linking error
Pelagicore/softwarecontainer pull request #62
Opened 2016-10-06 12:30 UTC by dzudek

During linking following error occurs:

	Linking CXX executable softwarecontainercommontest
	../libsoftwarecontainercommon.so: undefined reference to `json_integer_value'
	../libsoftwarecontainercommon.so: undefined reference to `json_string_value'
	../libsoftwarecontainercommon.so: undefined reference to `json_object_get'
	collect2: error: ld returned 1 exit status

2016-10-06 13:55 UTC, frznlogic approved these changes

2016-10-06 14:12 UTC, frznlogic requested changes
Need CLA setup before we can do this. Please hold on.

2016-10-13 14:15 UTC, DunderRoffe commented
I am struggling to understand why this is a problem. What this patch fixes is already done in "agent/CMakeLists.txt" and "libsoftwarecontainer/CMakeLists.txt".

What version of Jansson are you running on your system?
Adding an issue of checking required library versions.

2016-10-16 14:03 UTC, closed without merging

2016-12-02 11:54 UTC, tobsan commented
@dzudek Could you create a new pull request with the sigc++ and jansson fixes you had? We have got the CLA in place now so we are able to accept contributions.