WIP: Reading capabilities from disk
Pelagicore/softwarecontainer pull request #69
Opened 2016-10-11 13:09 UTC by thenor

Parses capability from Service Manifest files and returns GatewayConfigurations.

2016-10-11 13:42 UTC, tobsan reviewed
From the looks of this it looks like we'll be reading in capabilities from file on demand. Am I reading it correct then? If so, that should be changed to reading all of them at once and then do a lookup in some data structure on demand.

2016-10-11 13:42 UTC, tobsan commented on agent/src/capability/configstore.cpp
> +    static std::vector<GatewayConfiguration> capFromDir(std::string capID, std::string &configDirPath);
Indentation error?

2016-10-11 13:43 UTC, thenor commented on agent/src/capability/configstore.cpp
> +    static std::vector<GatewayConfiguration> capFromDir(std::string capID, std::string &configDirPath);
Copy paste error from the h file. I saw this myself. I also saw that my cpp and h files are not aligned at all. Sorry about that.

2016-10-11 14:01 UTC, thenor commented on agent/src/capability/configstore.h
> +    static bool parseGatewayData(const pelagicore::JSonElement &gatewayData, std::vector<Gateway> &gateways, std::string *error);
"const json_t *element" ?? Not "const pelagicore::JSonElement &gatewayData" ??

2016-10-11 15:25 UTC, DunderRoffe reviewed
Seems good overall, but the indentation is a bit off.

2016-10-11 15:25 UTC, DunderRoffe commented on agent/src/capability/configstore.cpp
> +								 std::string &filePath)
fix indentaion

2016-10-11 15:25 UTC, DunderRoffe commented on agent/src/capability/configstore.cpp
> +								      const std::string &filePath) {
align `const std::string &filePath` with `std::string capID`

2016-10-11 15:25 UTC, DunderRoffe commented on agent/src/capability/configstore.cpp
> +								 std::string &filePath)
Since `filePath` is const in getGatewayCap(...), maybe `filePath` could be const here as well?

2016-10-11 15:33 UTC, DunderRoffe commented on agent/src/capability/configstore.cpp
> +								      const std::string &filePath) {
This applies generally in the file

2016-10-11 18:01 UTC, frznlogic requested changes
Looks like you are started. Some minor comments here and there. I think the getGatewaysByCap could use some breaking apart, possibly some generalization as well. Perhaps something in the jsonparser?

2016-10-11 18:01 UTC, frznlogic commented on agent/src/capability/configstore.h
> +class ConfigStore
I'd love some documentation on what ConfigStore is.

2016-10-11 18:01 UTC, frznlogic commented on agent/src/capability/configstore.h
> +    static std::vector<GatewayConfiguration> getGatewaysByCap(std::string capID, const std::string &filePath);
Some of these declarations wind up really long, not sure if what we say about using namespace, and also maybe declare a new datatype for vector<GatewayConfiguration>. Just a thought.

2016-10-11 18:01 UTC, frznlogic commented on agent/src/capability/configstore.cpp
> +								      const std::string &filePath) {
the { of functions are supposed to be on a new line?

2016-10-11 18:01 UTC, frznlogic commented on agent/src/capability/configstore.cpp
> +			  GatewayConfiguration gw = GatewayConfiguration(gatewayName, gwConf);
There's a lot of nesting going on here... can the function be broken down?

2016-10-11 18:01 UTC, frznlogic commented on agent/src/capability/configstore.cpp
> +bool softwarecontainer::hasEnding(std::string const &fullString, std::string const &ending)
These  functions are declared in the softwarecontainer::ConfigStore in the header file, but here they are in softwarecontaner:: only?

2016-10-11 18:01 UTC, frznlogic commented on agent/src/capability/configstore.cpp
> +/*
Why is this commented out?

2016-10-11 18:01 UTC, frznlogic commented on agent/src/capability/configstore.cpp
> +            if (pelagicore::has_suffix(filename, ".json"))
No if without {}

2016-10-11 18:01 UTC, frznlogic commented on agent/src/capability/configstore.cpp
> +
Too many empty lines.

2016-10-11 18:01 UTC, frznlogic commented on agent/src/capability/configstore.cpp
> +			  log_debug() << "Error in " << pathString << ": " << strError;
Indentation in general is wrong. (2 spaces only here)

2016-10-13 07:41 UTC, closed without merging

2016-10-13 07:43 UTC, thenor commented
Thanks for all the comments. I will go through them and some might be inapplicable in the new pull request. Stay tuned!