WIP : Documentation of configuration mechanisms
Pelagicore/softwarecontainer pull request #86
Opened 2016-10-21 10:29 UTC by kursatkobya

2016-10-21 11:04 UTC, frznlogic commented
Please rebase the branch instead of merging it.

2016-10-21 11:09 UTC, frznlogic requested changes

2016-10-21 11:09 UTC, frznlogic commented on doc/chapters/design/index.rst
> +.. _design:
As far as I can see, noone is refering to this anchor?

2016-10-21 11:09 UTC, frznlogic commented on doc/chapters/configuration/index.rst
> +**--preload <num>** Number of containers to preload, defaults to 0
Should also mention the short versions of the command options imho.

2016-10-21 11:09 UTC, frznlogic commented on doc/chapters/configuration/index.rst
> +There is ``softwarecontainer.conf`` file to define many options used by The linux containers (lxc). It is possible to configure back-end container with this file. For more information about LXC confi
Is that going to be properly linked?

2016-10-21 11:14 UTC, kursatkobya commented on doc/chapters/design/index.rst
> +.. _design:
doc/chapters/configuration/index.rst:47 is referring there

2016-10-21 11:46 UTC, kursatkobya commented on doc/chapters/configuration/index.rst
> +There is ``softwarecontainer.conf`` file to define many options used by The linux containers (lxc). It is possible to configure back-end container with this file. For more information about LXC confi
it is actually linked properly. I have checked it from html.

2016-10-21 11:47 UTC, kursatkobya commented on doc/chapters/configuration/index.rst
> +**--preload <num>** Number of containers to preload, defaults to 0
Good Point

2016-10-24 08:41 UTC, tobsan requested changes

2016-10-24 08:41 UTC, tobsan commented on doc/chapters/configuration/index.rst
> +FILES
Change this to Files

2016-10-24 08:41 UTC, tobsan commented on doc/chapters/configuration/index.rst
> +As it is indicated in :ref:`design chapter <design>`, each IPC is managed by a gateway and each gateway has individual service manifest which maps capabilities to gateway configurations. The capabili
The wording is sort of backwards here. The gateways have no service manifests. How about this: "...each IPC is managed by a gateway. Service manifests contains capabilities, which maps to gateway configurations..."

Also, I don't think it makes sense to hard code the absolute path to where capabilities should be. This should be substituted in CMake when finished, then you could use a substitution in conf.py.in.

2016-10-24 08:41 UTC, tobsan commented on doc/chapters/configuration/index.rst
> +CMake options can be used to configure softwareContainer. The ``libsoftwarecontainer/src/CMakeLists.txt`` file can be edited for enabling/disabling desired gateways. (Currently following gateways are
You don't want to edit the file - the enabling/disabling of gateways is done at compile-time by passing flags to cmake.

2016-10-24 08:59 UTC, kursatkobya commented on doc/chapters/configuration/index.rst
> +As it is indicated in :ref:`design chapter <design>`, each IPC is managed by a gateway and each gateway has individual service manifest which maps capabilities to gateway configurations. The capabili
I just remove path sentence. Since we are already referencing service manifests section. It will be explained in there as well.

2016-10-24 10:18 UTC, kursatkobya commented on doc/chapters/configuration/index.rst
> +CMake options can be used to configure softwareContainer. The ``libsoftwarecontainer/src/CMakeLists.txt`` file can be edited for enabling/disabling desired gateways. (Currently following gateways are
Done

2016-10-24 10:25 UTC, tobsan approved these changes

2016-10-24 11:16 UTC, frznlogic approved these changes

2016-10-24 11:19 UTC, frznlogic commented on doc/chapters/configuration/index.rst
> +There is ``softwarecontainer.conf`` file to define many options used by The linux containers (lxc). It is possible to configure back-end container with this file. For more information about LXC confi
ok!

2016-10-24 11:19 UTC, frznlogic commented on doc/chapters/design/index.rst
> +.. _design:
ok!

2016-10-24 13:33 UTC, merged